#PBS -lwalltime=22:00:00
#PBS -lselect=1:ncpus=16:mem=96gb:ngpus=1:gpu_type=RTX6000

module load anaconda3/personal
module load cuda/10.2
source activate cardiax

python /rds/general/user/sg6513/home/repos/cardiax/train.py --frames_in 3 --frames_out 1 --step 5 --n_layers 20 --n_filters 16 --lr 0.0001 --n_workers 12 --gpu -1 --n_workers 3 --distributed_backend ddp --root '/rds/general/user/sg6513/ephemeral/data/' --logdir /rds/general/user/sg6513/ephemeral/data/logs --batch_size 32