#PBS -lwalltime=22:00:00
#PBS -lselect=1:ncpus=16:mem=96gb:ngpus=4:gpu_type=RTX6000

module load anaconda3/personal
source activate fk


python /rds/general/user/ep119/home/repos/fenton_karma_jax/deepexcite/resnet.py --frames_in 3 --frames_out 1 --step 5 --n_layers 20 --n_filters 16 --n_workers 12 --gpus -1 --n_workers 14 --distributed_backend ddp --root '/rds/general/user/ep119/ephemeral/data/deepexcite' --batch_size 32
